package controlsync

// Agent self-registration (§92.2).
//
// This is what makes the Partner-facing story true rather than merely stated.
// The documented contract has always said "the Agent generates a P-256 keypair
// locally and sends only the public half" — but the Agent could not do it. The
// key was generated by an Oolix-authored provisioning script that never shipped
// in the Partner pack, so a Partner following the documentation had no way to
// register at all.
//
// Generating the key in the binary that uses it also strengthens the guarantee:
// the private half is created inside the Partner's process, written to their
// disk, and never handled by anything Oolix wrote in a language they cannot
// read.

import (
	"bytes"
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"math/big"
	"net/http"
	"os"
	"path/filepath"
	"time"
)

// RegistrationResult is what Oolix returns once it accepts the public key.
type RegistrationResult struct {
	AgentID       string `json:"agent_id"`
	ClientID      string `json:"client_id"`
	TokenEndpoint string `json:"token_endpoint"`
	Issuer        string `json:"issuer"`
	Audience      string `json:"audience"`
	// The Partner organization the Agent now acts for, and the pinned values
	// its manifests are checked against. Older control planes omit them; the
	// setup page needs them to finish without hand-editing a config file.
	PartnerOrgID     string `json:"partner_org_id,omitempty"`
	ManifestIssuer   string `json:"manifest_issuer,omitempty"`
	ManifestAudience string `json:"manifest_audience,omitempty"`
}

type registerRequest struct {
	BootstrapToken string            `json:"bootstrap_token"`
	PublicKeyJWK   map[string]string `json:"agent_public_key_jwk"`
	AgentVersion   string            `json:"agent_version"`
	Capabilities   []string          `json:"capabilities"`
}

// Register exchanges a single-use bootstrap token for a lasting identity.
//
// The keypair is generated here, first. If registration fails the private key
// is discarded rather than written, so a half-finished attempt cannot leave a
// key on disk that Oolix has never heard of.
func Register(
	ctx context.Context,
	client *http.Client,
	apiBaseURL string,
	bootstrapToken string,
	privateKeyPath string,
	capabilities []string,
) (*RegistrationResult, error) {
	if bootstrapToken == "" {
		return nil, fmt.Errorf("a bootstrap token is required to register")
	}
	if privateKeyPath == "" {
		return nil, fmt.Errorf("private_key_path must be set before registering")
	}
	if _, err := os.Stat(privateKeyPath); err == nil {
		// Overwriting would strand the identity Oolix already knows about, and
		// the Agent would then fail to authenticate with no obvious cause.
		return nil, fmt.Errorf(
			"a private key already exists at %s; remove it deliberately to re-register",
			privateKeyPath)
	}

	// Prove the key can be written BEFORE spending the token.
	//
	// Registration is a one-way step: the token is single-use, and the identity
	// exists in Oolix the moment the call returns. Discovering afterwards that
	// the directory is read-only leaves an Agent listed in the Partner's
	// console that can never authenticate, and a token that cannot be reused.
	// A container running unprivileged against a root-owned volume does exactly
	// this, which is not an exotic setup — it is the default one.
	if err := checkKeyPathWritable(privateKeyPath); err != nil {
		return nil, err
	}

	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, fmt.Errorf("generate keypair: %w", err)
	}

	body, err := json.Marshal(registerRequest{
		BootstrapToken: bootstrapToken,
		PublicKeyJWK:   publicJWK(&key.PublicKey),
		AgentVersion:   Version,
		Capabilities:   capabilities,
	})
	if err != nil {
		return nil, fmt.Errorf("encode registration: %w", err)
	}

	reqCtx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	req, err := http.NewRequestWithContext(
		reqCtx, http.MethodPost, apiBaseURL+"/agent/v1/register", bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")

	res, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("register: %w", err)
	}
	defer func() { _ = res.Body.Close() }()

	if res.StatusCode != http.StatusCreated && res.StatusCode != http.StatusOK {
		var detail bytes.Buffer
		_, _ = detail.ReadFrom(res.Body)
		return nil, fmt.Errorf("register returned %d: %s", res.StatusCode, detail.String())
	}

	var result RegistrationResult
	if err := json.NewDecoder(res.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("decode registration response: %w", err)
	}
	if result.AgentID == "" || result.ClientID == "" {
		return nil, fmt.Errorf("registration response is missing an agent or client id")
	}

	// Only now is the key worth keeping.
	if err := writePrivateKey(privateKeyPath, key); err != nil {
		return nil, err
	}

	return &result, nil
}

// publicJWK renders the public half in the shape §92.2 specifies.
//
// The coordinates are fixed-width and base64url without padding, as JWK
// requires: a big.Int's own encoding drops leading zero bytes, which produces a
// key that is subtly wrong and fails verification rather than parsing.
func publicJWK(pub *ecdsa.PublicKey) map[string]string {
	size := (pub.Curve.Params().BitSize + 7) / 8
	return map[string]string{
		"kty": "EC",
		"crv": "P-256",
		"x":   base64url(pub.X, size),
		"y":   base64url(pub.Y, size),
	}
}

func base64url(n *big.Int, size int) string {
	b := n.Bytes()
	if len(b) < size {
		padded := make([]byte, size)
		copy(padded[size-len(b):], b)
		b = padded
	}
	return base64.RawURLEncoding.EncodeToString(b)
}

// checkKeyPathWritable confirms the key can be stored, without storing anything.
//
// The error names the directory and the user, because the cause is almost
// always a volume owned by root mounted into a container that runs as somebody
// else — and "permission denied" alone sends people to the wrong place.
func checkKeyPathWritable(path string) error {
	dir := filepath.Dir(path)
	if dir == "" {
		dir = "."
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf(
			"cannot create %s for the private key: %w\n"+
				"  the agent runs as uid %d; give that user ownership of the directory",
			dir, err, os.Getuid())
	}

	probe := filepath.Join(dir, ".oolix-write-probe")
	f, err := os.OpenFile(probe, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		return fmt.Errorf(
			"cannot write to %s: %w\n"+
				"  the agent runs as uid %d. If this is a mounted volume, it is probably\n"+
				"  owned by root — chown it to that uid, or set fsGroup in the pod spec.\n"+
				"  Refusing to register: the bootstrap token would be spent and the\n"+
				"  resulting identity unusable.",
			dir, err, os.Getuid())
	}
	_ = f.Close()
	_ = os.Remove(probe)
	return nil
}

// writePrivateKey stores the key at 0600, creating the directory if needed.
func writePrivateKey(path string, key *ecdsa.PrivateKey) error {
	der, err := x509.MarshalPKCS8PrivateKey(key)
	if err != nil {
		return fmt.Errorf("encode private key: %w", err)
	}

	if dir := filepath.Dir(path); dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o700); err != nil {
			return fmt.Errorf("create key directory: %w", err)
		}
	}

	// O_EXCL so a concurrent start cannot overwrite a key that was just written.
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		return fmt.Errorf("create key file: %w", err)
	}
	defer func() { _ = f.Close() }()

	if err := pem.Encode(f, &pem.Block{Type: "PRIVATE KEY", Bytes: der}); err != nil {
		return fmt.Errorf("write private key: %w", err)
	}
	return nil
}
