#!/usr/bin/env node
/**
 * Provision a real Partner Agent identity and write its local config.
 *
 * Performs the §92 registration a Partner operator would do once:
 *
 *   1. PARTNER_SECURITY_ADMIN mints a single-use bootstrap token
 *   2. the Agent generates a P-256 keypair LOCALLY
 *   3. registration exchanges the bootstrap token for an agent identity
 *   4. the private key is written as PEM, mode 0600
 *
 * The private key never leaves this machine, which is what makes an Agent's
 * signature meaningful (§92.2).
 *
 * Usage: node scripts/provision-agent.mjs [--partner A|B]
 */
import { generateKeyPair, exportPKCS8, exportJWK } from 'jose';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { seedToken } from './lib/onboard-partner.mjs';
import { findAgentPort } from './lib/agent-port.mjs';

const API = process.env.API_PUBLIC_URL ?? 'http://localhost:4000';

const PARTNERS = {
  A: {
    orgId: '22222222-2222-4222-8222-222222222222',
    securityUser: 'partner.security@example.test',
    dsn: 'postgres://oolix_agent_ro:agent-local-only@localhost:5433/partner_audience',
  },
  B: {
    orgId: '33333333-3333-4333-8333-333333333333',
    securityUser: 'partnerb.admin@example.test',
    dsn: 'postgres://oolix_agent_ro:agent-local-only@localhost:5433/partner_audience',
  },
};

// `indexOf` returns -1 when the flag is absent, and argv[0] is the node binary
// -- which is always defined, so the `?? 'A'` default could never fire and a
// bare `pnpm agent:provision` failed with the interpreter path as the partner.
const flagIndex = process.argv.indexOf('--partner');
const which = (
  process.argv.find((a) => a.startsWith('--partner='))?.split('=')[1] ??
  (flagIndex >= 0 ? process.argv[flagIndex + 1] : undefined) ??
  'A'
).toUpperCase();

const partner = PARTNERS[which];
if (!partner) {
  console.error(`unknown partner ${which}; expected A or B`);
  process.exit(1);
}

const agentDir = path.resolve('partner-agent', '.agent-state');
const keyPath = path.join(agentDir, 'agent-key.pem');
const configPath = path.resolve('partner-agent', 'config.local.yaml');

async function call(pathname, { method = 'GET', token, body } = {}) {
  const res = await fetch(`${API}${pathname}`, {
    method,
    headers: {
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
      ...(body ? { 'Content-Type': 'application/json' } : {}),
      'X-Org-Id': partner.orgId,
    },
    ...(body ? { body: JSON.stringify(body) } : {}),
  });
  const text = await res.text();
  const json = text ? JSON.parse(text) : null;
  if (!res.ok)
    throw new Error(`${method} ${pathname} -> ${res.status} ${json?.error?.message ?? text}`);
  return json;
}

console.log(`\nProvisioning a Partner Agent for Partner ${which} (spec §92)\n`);

const securityToken = await seedToken(partner.securityUser);

// §92.1
const { bootstrap_token } = await call('/v1/partner/agents/bootstrap-tokens', {
  method: 'POST',
  token: securityToken,
});
console.log('  1. bootstrap token minted (single-use, 15 minutes)');

// §92.2 -- the keypair is generated HERE, on Partner infrastructure.
const { privateKey, publicKey } = await generateKeyPair('ES256', { extractable: true });
const jwk = await exportJWK(publicKey);

const reg = await call('/agent/v1/register', {
  method: 'POST',
  body: {
    bootstrap_token,
    agent_public_key_jwk: { kty: jwk.kty, crv: jwk.crv, x: jwk.x, y: jwk.y },
    agent_version: '0.1.0',
    capabilities: ['PARTNER_WEB'],
  },
});
console.log(`  2. registered: agent_id=${reg.agent_id}`);

await mkdir(agentDir, { recursive: true });
// 0600: the Agent's private key must not be world-readable (§82).
await writeFile(keyPath, await exportPKCS8(privateKey), { mode: 0o600 });
console.log(`  3. private key written to ${keyPath} (mode 0600, never leaves this host)`);

// §69.1 makes the listen address the Partner's choice, and 8082 is only a
// default. Probed rather than assumed: Windows reserves TCP ranges dynamically
// for Hyper-V and WSL2, and a reserved port fails at bind with a permissions
// error that looks nothing like "port taken".
const listenPort = await findAgentPort();
if (listenPort !== 8082) {
  console.log(`  note: port 8082 is not bindable on this host; using ${listenPort} instead.`);
}

const config = `# Generated by scripts/provision-agent.mjs for Partner ${which}.
# Local development only. Regenerate with: pnpm agent:provision
agent:
  partner_id: "${partner.orgId}"
  listen_addr: "0.0.0.0:${listenPort}"
  control_sync_interval: 30s
  stale_grace: 15m
  decision_timeout: 100ms

oolix:
  api_base_url: "${API}"
  agent_id: "${reg.agent_id}"
  client_id: "${reg.client_id}"
  private_key_path: "./.agent-state/agent-key.pem"
  manifest_issuer: "${reg.issuer ?? API}"
  manifest_audience: "oolix-partner-agent"
  token_audience: "${reg.audience ?? 'oolix-agent-api'}"

connector:
  type: "postgres_view"
  dsn: "${partner.dsn}"
  membership_query: >-
    SELECT 1 FROM oolix_segment_membership
    WHERE partner_user_id = $1 AND segment_id = $2 AND expires_at > NOW()
  consent_query: >-
    SELECT (eligible AND withdrawn_at IS NULL) FROM oolix_user_consent
    WHERE partner_user_id = $1 AND purpose_id = $2
  max_open_conns: 10
  # Hard deadline, deliberately above §103's p95 OBJECTIVE of 30ms: a p95 used
  # as a per-request timeout fails the slowest 5% by construction.
  query_timeout: 50ms

  # ---------------------------------------------------------------------------
  # v6 §5.2: the Partner-local attribute mapping.
  #
  # This block is the whole reason v6 works without Oolix seeing Partner data.
  # Oolix asks about 'payment_method'; this Partner stores 'pay_mode'. Oolix asks
  # about 'age'; this Partner stores a date of birth. The translation lives HERE,
  # in the Partner's own config file, and §17 keeps it here: Oolix stores
  # "Partner capability metadata, not Partner local field names".
  #
  # Nothing Oolix sends can add to this map. An attribute that is absent is one
  # this Partner cannot be asked about -- §7 turns that into INCOMPATIBLE for a
  # REQUIRED rule, which is the honest answer rather than a partial match.
  audience:
    # §5.2: a restricted, PRE-COMPUTED table. Never a live join across the
    # production transactional schema.
    attribute_table: "oolix_audience_attributes"
    # Reported with every estimate so an answer can be tied to the mapping that
    # produced it (§8.2, §16). Bump it whenever anything below changes.
    mapping_version: 8
    # An estimate is a full-table count a Buyer waits seconds for, not an ad
    # decision on a page render. Deliberately far above query_timeout.
    evaluation_timeout: 30s
    # §11: how long a compiled audience stays servable before a rebuild. The
    # worker refreshes at half this, so members never expire under a live
    # campaign.
    materialization_ttl: 24h

    mapping:
      # --- demographic ------------------------------------------------------
      # §5.2's own example of a derived attribute: Oolix asks for an age band,
      # this Partner stores a birth date and never sends either.
      age:
        # column/derive make this indexable. Without them the function wraps
        # the column and no index on dob applies, so every audience carrying an
        # age rule reads the whole table.
        expr: "date_part('year', age(dob))"
        type: "NUMBER"
        column: dob
        derive: years_since
      gender:
        expr: "sex_code"
        type: "ENUM"

      # --- geography --------------------------------------------------------
      country:
        expr: "country_code"
        type: "ENUM"
      state_region:
        expr: "region_code"
        type: "ENUM"
      city:
        expr: "city_code"
        type: "ENUM"

      # --- commerce ---------------------------------------------------------
      online_shopper:
        expr: "is_online_buyer"
        type: "BOOLEAN"
      purchase_category:
        expr: "product_class"
        type: "ENUM"
      purchase_recency_days:
        expr: "date_part('day', now() - last_order_at)"
        type: "NUMBER"
        column: last_order_at
        derive: days_since
      purchase_frequency:
        expr: "order_count_90d"
        type: "NUMBER"
      payment_method:
        expr: "pay_mode"
        type: "ENUM"

      # --- travel -----------------------------------------------------------
      recent_booking:
        expr: "has_recent_trip"
        type: "BOOLEAN"
      domestic_international:
        expr: "trip_scope"
        type: "ENUM"
      booking_recency_days:
        expr: "date_part('day', now() - last_booking_at)"
        type: "NUMBER"
        column: last_booking_at
        derive: days_since

      # --- engagement -------------------------------------------------------
      active_user_days:
        expr: "date_part('day', now() - last_seen_at)"
        type: "NUMBER"
        column: last_seen_at
        derive: days_since
      app_active:
        expr: "uses_app"
        type: "BOOLEAN"
      loyalty_tier:
        expr: "tier_code"
        type: "ENUM"

state:
  mode: "embedded"
  path: "./.agent-state"
  redis_key_prefix: "oolix:agent"

channels:
  meta:
    enabled: false
  google:
    enabled: false

logging:
  level: "debug"
  format: "json"
  redact_fields:
    - "partner_user_id"
    - "email"
    - "phone"
    - "mobile_id"
`;

await writeFile(configPath, config);
console.log(`  4. config written to ${configPath}`);
console.log(`\nStart the Agent with:  pnpm agent:run\n`);
